services:
  qdrant:
    image: qdrant/qdrant:v1.19.1
    container_name: acme-qdrant
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    volumes:
      - ./indexes/qdrant_storage:/qdrant/storage
    restart: unless-stopped
